compile_lorenz:
	g++ -std=c++17 -larmadillo lorenz.cpp -o lorenz

compile_spiral:
	g++ -std=c++17 -larmadillo spiral.cpp -o spiral

run_lorenz:
	./lorenz $(particles) $(tf) $(delta_t)

run_spiral:
	./spiral $(particles) $(tf) $(delta_t)